# Generated by Django 3.1.5 on 2021-01-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='pics')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('companyName', models.CharField(max_length=50)),
                ('contactPhone', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('companySite', models.CharField(max_length=50)),
                ('language', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Gujarati', 'Gujarati')], default='Gujarati', max_length=50)),
                ('timeZone', models.CharField(max_length=50)),
                ('communication', models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS'), ('Phone', 'Phone')], max_length=50)),
                ('passwordRV', models.BooleanField(default=False)),
                ('address1', models.TextField()),
                ('address2', models.TextField()),
                ('postcode', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
    ]
