# Generated by Django 3.1.5 on 2021-01-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlhome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradd',
            name='contactPhone',
            field=models.CharField(max_length=11),
        ),
    ]
