# Generated by Django 3.1.5 on 2021-01-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlhome', '0002_auto_20210106_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradd',
            name='communication',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='useradd',
            name='language',
            field=models.CharField(max_length=50),
        ),
    ]
